version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/timi131/ssl:/etc/nginx/ssl:ro
    restart: always