version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my_website
    ports:
      - "80:80"  # Пробрасываем порт 80 контейнера на порт 80 сервера
    volumes:
      # Монтируем код нашего сайта в стандартную директорию Nginx
      - ./src:/usr/share/nginx/html:ro
      # Монтируем наш конфиг Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always